import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#fbf8f8',
        'tertiary-fixed': '#ffdad7',
        'error-container': '#ffdad6',
        'surface-dim': '#e0d8d8',
        'tertiary': '#733430',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'surface-bright': '#fff8f8',
        'on-secondary-container': '#2f1515',
        'on-tertiary': '#ffffff',
        'secondary-container': '#ffdad8',
        'on-primary-fixed': '#3f0007',
        'surface-container': '#f5f0f0',
        'tertiary-container': '#904a46',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#ffb3b6',
        'on-primary': '#ffffff',
        'inverse-primary': '#ffb3b6',
        'on-surface': '#201a1a',
        'inverse-surface': '#362f2f',
        'surface-tint': '#b52434',
        'outline': '#857372',
        'on-primary-fixed-variant': '#710014',
        'surface': '#fff8f8',
        'tertiary-fixed-dim': '#e6bdb8',
        'surface-variant': '#f4dddc',
        'surface-container-highest': '#eadddc',
        'inverse-on-surface': '#fbeeec',
        'on-background': '#201a1a',
        'on-tertiary-container': '#ffdad7',
        'background': '#fff8f8',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#e7bdbb',
        'on-surface-variant': '#524343',
        'on-secondary-fixed': '#2c1514',
        'primary-fixed': '#ffdadb',
        'primary': '#b52434',
        'on-tertiary-fixed-variant': '#591f1c',
        'on-primary-container': '#ffdadb',
        'outline-variant': '#d7c1c1',
        'surface-container-high': '#efeaea',
        'error': '#ba1a1a',
        'on-secondary-fixed-variant': '#5d3f3e',
        'secondary': '#775655',
        'primary-container': '#900223',
        'on-tertiary-fixed': '#2c0504',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      typography: {
        DEFAULT: {
          css: {
            color: '#201a1a',
            a: { color: '#b52434' },
            h1: { fontFamily: 'Plus Jakarta Sans, sans-serif', color: '#201a1a' },
            h2: { fontFamily: 'Plus Jakarta Sans, sans-serif', color: '#201a1a' },
            h3: { fontFamily: 'Plus Jakarta Sans, sans-serif', color: '#201a1a' },
          },
        },
      },
    },
  },
  plugins: [],
}
export default config
