import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface':                  'var(--surface)',
        'surface-container-low':    'var(--surface-container-low)',
        'surface-container':        'var(--surface-container)',
        'surface-container-high':   'var(--surface-container-high)',
        'surface-container-highest':'var(--surface-container-highest)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-dim':              'var(--surface-dim)',
        'surface-bright':           'var(--surface-bright)',
        'surface-variant':          'var(--surface-variant)',
        'on-surface':               'var(--on-surface)',
        'on-surface-variant':       'var(--on-surface-variant)',
        'on-background':            'var(--on-background)',
        'background':               'var(--background)',
        'primary':                  'var(--primary)',
        'primary-container':        'var(--primary-container)',
        'on-primary':               'var(--on-primary)',
        'on-primary-container':     'var(--on-primary-container)',
        'outline':                  'var(--outline)',
        'outline-variant':          'var(--outline-variant)',
        'error':                    'var(--error)',
        'error-container':          'var(--error-container)',
        'secondary':                'var(--secondary)',
        'secondary-container':      'var(--secondary-container)',
        'on-secondary':             'var(--on-secondary)',
        'on-secondary-container':   'var(--on-secondary-container)',
        'inverse-surface':          'var(--inverse-surface)',
        'inverse-on-surface':       'var(--inverse-on-surface)',
        'inverse-primary':          'var(--inverse-primary)',
        // Keep static aliases that are used directly
        'tertiary':                 '#733430',
        'tertiary-container':       '#904a46',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#ffdad7',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
        'primary-fixed':            '#ffdadb',
        'primary-fixed-dim':        '#ffb3b6',
        'on-primary-fixed':         '#3f0007',
        'on-primary-fixed-variant': '#710014',
        'secondary-fixed':          '#ffdad8',
        'secondary-fixed-dim':      '#e7bdbb',
        'on-secondary-fixed':       '#2c1514',
        'on-secondary-fixed-variant':'#5d3f3e',
        'tertiary-fixed':           '#ffdad7',
        'tertiary-fixed-dim':       '#e6bdb8',
        'on-tertiary-fixed':        '#2c0504',
        'on-tertiary-fixed-variant':'#591f1c',
        'surface-tint':             '#b52434',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body:     ['Plus Jakarta Sans', 'sans-serif'],
        label:    ['Plus Jakarta Sans', 'sans-serif'],
      },
      typography: {
        DEFAULT: {
          css: {
            color: 'var(--on-surface)',
            a: { color: 'var(--primary)' },
            h1: { fontFamily: 'Plus Jakarta Sans, sans-serif', color: 'var(--on-surface)' },
            h2: { fontFamily: 'Plus Jakarta Sans, sans-serif', color: 'var(--on-surface)' },
            h3: { fontFamily: 'Plus Jakarta Sans, sans-serif', color: 'var(--on-surface)' },
          },
        },
      },
    },
  },
  plugins: [],
}
export default config
